version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - frontend
    # ...

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # ...
