version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - frontend
    # ...

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # ...

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data-test:
